http:
  services:

    # Weighted round robin service
    wrr1-svc:
      weighted:
        # sticky:
        #   cookie:
        #     name: lvl1
        services:
          - name: whoami1-svc # Service defined below
            weight: 3
          - name: whoami2-svc # Service defined below
            weight: 1

    whoami1-svc:
      loadBalancer:
        # sticky:
        #   cookie:
        #     name: lvl2
        # healthCheck:
        #   path: /health
        #   port: 8080
        #   interval: "10s"
        #   timeout: "3s"
        servers:
          # Test containers running on host (sample-external-service/docker-compose.yml)
          - url: http://host.docker.internal:8081
          - url: http://host.docker.internal:8082

    whoami2-svc:
      loadBalancer:
        # sticky:
        #   cookie:
        #     name: lvl2
        servers:
          # Test containers running on host (sample-external-service/docker-compose.yml)
          - url: http://host.docker.internal:8083
          - url: http://host.docker.internal:8084