version: '3'

# Make this container run in the 'traefik' network
networks:
  default:
    name: traefik

services:
  whoami:
    image: traefik/whoami
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-router.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.whoami-router.entrypoints=websecure"
      - "traefik.http.routers.whoami-router.tls.certresolver=letsencrypt-resolver"
      - "traefik.http.routers.whoami-router.middlewares=my-custom-auth-middleware@file"
